library(tidyverse)
library(readxl)
library(data.table)
library(janitor)

# read in aamc data files
file_list <- list.files("data/AAMC")

for (num in seq_along(file_list)) {
  read_excel(paste0("data/AAMC/",file_list[num])) %>% 
    colnames(.)[1] %>% 
    colnames(.) %>% 
    gsub(".*: ","",.) -> specialty_name
  
  read_excel(paste0("data/AAMC/",file_list[num]),skip = 1)  %>% 
    colnames(.) %>% 
    .[-1] -> ID
  
  read_excel(paste0("data/AAMC/",file_list[num]), skip = 1) %>% 
    t(.) %>% 
    as.data.frame(.) %>% 
    row_to_names(row_number = 1) %>% 
    mutate(Specialty = specialty_name, .before = 1) %>% 
    mutate(ID = ID, .before = 1)-> out
  
  if(num == 1) {
    dat <- out
  } else {
    dat <- bind_rows(dat,out)
  }
}

# Remove duplicates and check to ensure have the correct number of programs in each speciality
dat <- unique(dat)
dat %>% 
  group_by(Specialty) %>% 
  summarize(count = n()) %>% 
  View(.)

# Remove duplicates


dat %>% 
  filter(Specialty == "Psychiatry") %>% 
  .$`Residency program name` %>% 
  unique(.) -> included

full_list <- c('University of Alabama Medical Center Program',
                "St. John's Episcopal Hospital-South Shore Program",
                'Jamaica Hospital Medical Center Program',
                'University at Buffalo Program',
                'BronxCare Health System Program',
                'New York Presbyterian Hospital (Columbia Campus)/New York State Psychiatric Institute Program',
                'Zucker School of Medicine at Hofstra/Northwell at Zucker Hillside Hospital Program',
                'Maimonides Medical Center Program',
                'NYU Grossman School of Medicine Program',
                'SUNY Downstate Health Sciences University Program',
                'Stony Brook Medicine/University Hospital Program',
                'SUNY Upstate Medical University Program',
                'Westchester Medical Center Program',
                'Icahn School of Medicine at Mount Sinai (Morningside/West) Program',
                'Albany Medical Center Program',
                'Richmond University Medical Center Program',
                'Carolinas Medical Center Program',
                'Campbell University Program',
                'Cone Health Program',
                'University of North Carolina Hospitals Program',
                'Duke University Hospital Program',
                'Vidant Medical Center/East Carolina University Program',
                'Wake Forest University School of Medicine Program',
                'University of North Dakota Program',
                'Adena Regional Medical Center Program',
                'OhioHealth/Riverside Methodist Hospital Program',
                'Akron General Medical Center Program',
                'University of Cincinnati Medical Center/College of Medicine Program',
                'Case Western Reserve University/University Hospitals Cleveland Medical Center Program',
                'Wright State University Program',
                'Summa Health System/NEOMED Program',
                'Mountain Area Health Education Center Program',
                'University of Toledo Program',
                'Creedmoor Psychiatric Center Program',
                'University of Rochester Program',
                'University of Nevada Las Vegas (UNLV) School of Medicine Program',
                'Dartmouth-Hitchcock/Mary Hitchcock Memorial Hospital Program',
                'RowanSOM/Jefferson Health/Virtua Our Lady of Lourdes Hospital Program',
                'Ocean Medical Center Program',
                'Jersey Shore University Medical Center Program',
                'AtlantiCare Regional Medical Center Program',
                'New Bridge Medical Center Program',
                'Rutgers Health/Trinitas Regional Medical Center Program',
                'Rutgers Health/New Jersey Medical School Program',
                'Rutgers Health/Robert Wood Johnson Medical School Program',
                'Cooper Medical School of Rowan University/Cooper University Hospital Program',
                'University of New Mexico School of Medicine Program',
                'Zucker School of Medicine at Hofstra/Northwell at Staten Island University Hospital Program',
                'St Barnabas Hospital Program',
                'Icahn School of Medicine at Mount Sinai (NYC Health and Hospitals: Elmhurst) Program',
                'Zucker School of Medicine at Hofstra/Northwell at Mather Hospital Program',
                'Garnet Health Medical Center Program',
                'Arnot Ogden Medical Center Program',
                'Stony Brook Medicine Program',
                'Nuvance Health Program',
                'Rochester General Hospital Program',
                'Nassau University Medical Center Program',
                'Montefiore Medical Center/Albert Einstein College of Medicine Program',
                'Lincoln Medical and Mental Health Center Program',
                'Icahn School of Medicine at Mount Sinai (Beth Israel) Program',
                'One Brooklyn Health System/Brookdale University Hospital and Medical Center Program',
                'Harlem Hospital Center Program',
                'Icahn School of Medicine at Mount Sinai (Mount Sinai Hospital) Program',
                'New York Presbyterian Hospital (Cornell Campus) Program',
                'New York Medical College (Metropolitan) Program',
                'One Brooklyn Health System/Interfaith Medical Center Program',
                'The MetroHealth System/Case Western Reserve University Program',
                'Ohio State University Hospital Program',
                'Cleveland Clinic Foundation Program',
                'Texas Institute for Graduate Medical Education and Research (TIGMER) Program',
                'Darnall Army Medical Center Program',
                'Texas A&M Health Science Center College of Medicine Program',
                'University of Texas Health Science Center at Tyler/UT Health Pittsburg Program',
                'Texas Tech University HSC El Paso/Hospitals of Providence Transmountain Campus Program',
                'University of Texas Medical Branch Hospitals Program',
                'Texas Tech University HSC El Paso Program',
                'University of Texas at Austin Dell Medical School Program',
                'University of Texas Southwestern Medical Center Program',
                'Baylor College of Medicine Program',
                'Texas Tech University Health Sciences Center at Lubbock Program',
                'Texas A&M College of Medicine-Scott and White Medical Center (Temple) Program',
                'John Peter Smith Hospital (Tarrant County Hospital District) Program',
                'University of Texas Health Science Center at Houston Program',
                'University of Texas Health Science Center at Tyler Program',
                'University of Texas Health Science Center San Antonio Joe and Teresa Lozano Long School of Medicine Program',
                'University of Vermont Medical Center Program',
                'HCA Healthcare LewisGale Medical Center Program',
                'Naval Medical Center (Portsmouth) Program',
                'University of Virginia Medical Center Program',
                'Eastern Virginia Medical School Program',
                'Virginia Commonwealth University Health System Program',
                'Carilion Clinic-Virginia Tech Carilion School of Medicine Program',
                'Providence Sacred Heart Medical Center Program',
                'University of Washington Program',
                'Marshall University School of Medicine Program',
                'West Virginia University Program',
                'Charleston Area Medical Center/West Virginia University (Charleston Division) Program',
                'Medical College of Wisconsin Affiliated Hospitals (Northeastern Wisconsin) Program',
                'Medical College of Wisconsin Affiliated Hospitals (Central Wisconsin) Program',
                'University of Utah Health Program',
                'Texas Tech University Health Sciences Center (Permian Basin) Program',
                'University of Texas RGV Program',
                'East Tennessee State University/Quillen College of Medicine Program',
                'Oklahoma State University Center for Health Sciences Program',
                'Oklahoma State University Center for Health Sciences/Griffin Memorial Hospital Program',
                'University of Oklahoma Health Sciences Center Program',
                'University of Oklahoma School of Community Medicine (Tulsa) Program',
                'Samaritan Health Services - Corvallis Program',
                'Oregon Health & Science University Program',
                'Geisinger Health System Program',
                'Wright Center for Graduate Medical Education Program',
                'Lake Erie College of Osteopathic Medicine Program',
                'St Luke’s Hospital – Anderson Campus Program',
                'Lehigh Valley Health Network Program',
                'Tower Health Program',
                'Penn State Milton S Hershey Medical Center Program',
                'Temple University Hospital Program',
                'Sidney Kimmel Medical College at Thomas Jefferson University/TJUH Program',
                'University of Pennsylvania Health System Program',
                'Allegheny Health Network Medical Education Consortium (AGH) Program',
                'Meharry Medical College Program',
                'University of Tennessee Program',
                'Vanderbilt University Medical Center Program',
                'HCA Healthcare/TriStar Nashville Program',
                'University of South Dakota Program',
                'Prisma Health/University of South Carolina SOM Columbia (Columbia) Program',
                'University of Nevada Reno School of Medicine Program',
                'Medical University of South Carolina Program',
                'Prisma Health/University of South Carolina SOM Greenville (Greenville) Program',
                'Butler Hospital/Brown University Program',
                'University of Puerto Rico Program',
                'Ponce Health Sciences University Program',
                'UPMC Medical Education Program',
                'Albert Einstein Healthcare Network Program',
                'Prisma Health/University of South Carolina SOM Greenville (Greer) Program',
                'University of Wisconsin Hospitals and Clinics Program',
                'HCA Healthcare Sunrise Health Graduate Medical Education Program',
                'University of Nebraska Medical Center College of Medicine Program',
                'Institute of Living/Hartford Hospital Program',
                'Christiana Care Health Services Inc Program',
                'Delaware Psychiatric Center Program',
                'MedStar Health/Georgetown University Hospital Program',
                'George Washington University Program',
                'Howard University Program',
                'Saint Elizabeths Hospital-DC Department of Behavioral Health Program',
                'National Capital Consortium Program',
                'Larkin Community Hospital Program',
                'University of Florida College of Medicine Jacksonville Program',
                'Florida Atlantic University Charles E. Schmidt College of Medicine Program',
                'Citrus Health Network, Inc. Program',
                'University of Central Florida/HCA Healthcare GME (Gainesville) Program',
                'HCA Healthcare/USF Morsani College of Medicine GME: Largo Medical Center Program',
                'University of Connecticut Program',
                'HCA Healthcare: East Florida Division GME: University Hospital and Medical Center Program',
                'Centerstone Program',
                'University of Central Florida/HCA Healthcare GME (Greater Orlando) Program',
                'HCA Healthcare/Mercer University School of Medicine/Orange Park Medical Center Program',
                'Memorial Healthcare System, Hollywood, Florida Program',
                'HCA Healthcare: East Florida Division GME: Aventura Hospital and Medical Center Program',
                'Mount Sinai Medical Center of Florida, Inc Program',
                'Nova Southeastern University - College of Osteopathic Medicine Program',
                'University of Florida Program',
                'University of Miami/Jackson Health System Program',
                'University of South Florida Morsani Program',
                'HCA Healthcare/Mercer University School of Medicine/Coliseum Medical Centers Program',
                'Gateway Behavioral Health Community Service Board Program',
                'Emory University School of Medicine Program',
                'Medical College of Georgia Program',
                'Community Health of South Florida, Inc. (CHI) Program',
                'Morehouse School of Medicine Program',
                'Yale-New Haven Medical Center Program',
                'HCA HealthONE Program',
                'USA Health Program',
                'University of Arizona College of Medicine-Phoenix Program',
                'University of Arizona College of Medicine-Tucson Program',
                'Creighton University School of Medicine (Phoenix) Program',
                'University of Arkansas for Medical Sciences (UAMS) College of Medicine Program',
                'Kaweah Delta Health Care District (KDHCD) Program',
                'Kaiser Permanente Southern California Program',
                'University of California Riverside School of Medicine Program',
                'Arrowhead Regional Medical Center Program',
                'Charles R Drew University of Medicine and Science, College of Medicine Program',
                'Kaiser Permanente Northern California (Oakland) Program',
                'Kaiser Permanente Northern California (San Jose) Program',
                'Olive View/UCLA Medical Center Program',
                'Riverside University Health System Program',
                'University of Colorado Program',
                'Community Memorial Health System Program',
                'Los Angeles County-Harbor-UCLA Medical Center Program',
                'University of California (San Francisco)/Fresno Program',
                'University of California (Irvine) Program',
                'Loma Linda University Health Education Consortium Program',
                'UCLA David Geffen School of Medicine/UCLA Medical Center Program',
                'University of California (San Diego) Medical Center Program',
                'University of California (San Francisco) Program',
                'Naval Medical Center (San Diego) Program',
                'California Pacific Medical Center Program',
                'San Mateo County Behavioral Health and Recovery Services Program',
                'UCLA-Kern Medical Center Program',
                'University of California Davis Health Program',
                'UCLA/VA Greater Los Angeles Program',
                'Stanford Health Care-Sponsored Stanford University Program',
                'University of Southern California/LAC+USC Medical Center Program',
                'Tripler Army Medical Center Program',
                'University of Hawaii Program',
                'University of Washington (Boise) Program',
                'Boston University Medical Center Program',
                "St Elizabeth's Medical Center Program",
                'Tufts Medical Center Program',
                'University of Massachusetts Program',
                'Boston VA Healthcare System (Brockton-West Roxbury)/Harvard Medical School Program',
                'Massachusetts General Hospital/McLean Hospital Program',
                "Brigham and Women's Hospital/Harvard Medical School Program",
                'UMMS-Baystate Program',
                'Pine Rest Christian Mental Health Services Program',
                'Central Michigan University College of Medicine Program',
                'Henry Ford Allegiance Health Program',
                'Detroit Wayne County Health Authority (Authority Health) GME Consortium Program',
                'Oakland Physicians Medical Center Program',
                'Beaumont Health Program',
                'Berkshire Medical Center Program',
                'St Mary Mercy Hospital Program',
                'Michigan State University Program',
                'Henry Ford Hospital/Wayne State University Program',
                'Detroit Medical Center/Wayne State University Program',
                'Western Michigan University Homer Stryker MD School of Medicine Program',
                'University of Minnesota Program',
                'Mayo Clinic College of Medicine and Science (Rochester) Program',
                'Hennepin Healthcare/Regions Hospital Program',
                'University of Mississippi Medical Center Program',
                'Kansas City University GME Consortium (KCU-GME Consortium)/Ozark Center Program',
                'Unity Health-White County Medical Center Program',
                'University of Missouri-Columbia Program',
                'University of Missouri-Kansas City School of Medicine Program',
                'St Louis University School of Medicine Program',
                'Washington University/B-JH/SLCH Consortium Program',
                'University of Michigan Health System Program',
                'Cambridge Health Alliance Program',
                'Beth Israel Deaconess Medical Center Program',
                'University of Maryland/Sheppard Pratt Program',
                'Carle Foundation Hospital Program',
                'Riverside Medical Center Program',
                'Mount Sinai Hospital Medical Center of Chicago Program',
                'Rush University Medical Center Program',
                'McGaw Medical Center of Northwestern University Program',
                'University of Illinois College of Medicine at Chicago Program',
                'Loyola University Medical Center Program',
                'Southern Illinois University Program',
                'Advocate Health Care (Advocate Lutheran General Hospital) Program',
                'University of Illinois College of Medicine at Peoria Program',
                'Chicago Medical School/Rosalind Franklin University of Medicine & Science Program',
                'University of Chicago Program',
                'Community Health Network, Inc. Program',
                'Indiana University School of Medicine (Vincennes) Program',
                'Indiana University School of Medicine (Merrillville) Program',
                'Indiana University School of Medicine (Indianapolis) Program',
                'Iowa Medical Education Collaborative Program',
                'Johns Hopkins University Program',
                'National Institutes of Health Clinical Center Program',
                'Maine Medical Center Program',
                'Louisiana State University Program',
                'Louisiana State University/Ochsner Clinic Foundation Program',
                'Louisiana State University (Shreveport) Program',
                'Creighton University School of Medicine (Omaha) Program',
                'Tulane University Program',
                'University of Kentucky College of Medicine Program',
                'University of Kentucky College of Medicine (Bowling Green) Program',
                'University of Kansas (Wichita) Program',
                'University of Kansas School of Medicine Program',
                'University of Iowa Hospitals and Clinics Program',
                'UnityPoint Broadlawns Psychiatry Education Foundation Program',
                'University of Louisville School of Medicine Program',
                'Medical College of Wisconsin Affiliated Hospitals (Milwaukee) Program')
